In [19]:
from base import GridWorld, Agent, RandomPolicy
from IPython.display import clear_output
import time

gw = GridWorld(size=np.array([3,4]), terminal=[1,3])

def play(env, agent, steps = 20):
    i = 0
    while env.isterminal() is not True and i < 40:
        gw.step(agent.step())
        clear_output(wait=True)
        gw.print()
        time.sleep(1)
        i+=1    
    
rp = RandomPolicy(gw)
# gw.print()

gw.step("down")
gw.print()

| | | | |  total_reward: -1
| | | |T|  steps: 0
|*| | | |  last action: down


In [23]:
gw.restart()
play(gw,rp)

| | | | |  total_reward: -22
| | | |*|  steps: 0
| | | | |  last action: down


In [2]:
print(gw)



| | | | | | | |  total_reward: -1
| | | |T| | | |  steps: 0
| | | | | | | |  last action: down
|*| | | | | | |
| | | | | | | |
| | | | | | | |
| | | | | | | |


In [22]:
def evaluate(env, agent, gamma, theta=0.01):
    # and please TODO: experiment, will it converge in case of random or different values??     
    # V = V_ = numpy.full((ROWS, COLS), value) # for different value
    # for random matrix... 
    # V = V_ = np.random.rand(ROWS, COLS)
    
    ROWS, COLS = gw.rows(), gw.cols()
    print(ROWS, '  ', COLS)
    V = V_ = np.zeros((ROWS,COLS))
    V[env.terminal[0], env.terminal[1]] = 0
    delta = theta*1.1 # first loop value
    print('here')
    print(V_[0,0])
    
    r,c = np.indices((ROWS,COLS))
    S = np.c_[r.ravel(), c.ravel()]
    print(S)
    
    print('---')
        
    run = True
    if run == True:
        q = 0
        while delta > theta and q < 20:
            q +=1
            for s in S:                  
                print('______s: ',s)
                
                actions = agent.pi(s)
                print(actions)
                total_reward = 0

                for a in actions:
                    print(a, actions[a])
                    srpairs = env.dynamics(a,s)
#                     print('pairs ', srpairs)
                    action_reward = 0
                    for srp in srpairs:
    #                       print('srp ', srp)
                        s_ = srp[0]
                        r = srp[1]
                        p = srp[2]
                        print('R: ', s_, r, p)
                        action_reward += r + gamma*V[tuple(s_)]

            print('final_action_reward: ', action_reward)
 

            delta = np.amax(abs(V_ - V))
            # sweep
            V = V_
    
    return V

print(gw.size)
evaluate(gw, rp, 0.9)

[3 4]
3    4
here
0.0
[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]]
---
______s:  [0 0]
{'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}
up 0.25
R:  [0 0] -1 1
down 0.25
R:  [1 0] -1 1
left 0.25
R:  [0 0] -1 1
right 0.25
R:  [0 1] -1 1
______s:  [0 1]
{'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}
up 0.25
R:  [0 1] -1 1
down 0.25
R:  [1 1] -1 1
left 0.25
R:  [0 0] -1 1
right 0.25
R:  [0 2] -1 1
______s:  [0 2]
{'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}
up 0.25
R:  [0 2] -1 1
down 0.25
R:  [1 2] -1 1
left 0.25
R:  [0 1] -1 1
right 0.25
R:  [0 3] -1 1
______s:  [0 3]
{'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}
up 0.25
R:  [0 3] -1 1
down 0.25
R:  [1 3] 0 1
left 0.25
R:  [0 2] -1 1
right 0.25
R:  [0 3] -1 1
______s:  [1 0]
{'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}
up 0.25
R:  [0 0] -1 1
down 0.25
R:  [2 0] -1 1
left 0.25
R:  [1 0] -1 1
right 0.25
R:  [1 1] -1 1
______s:  [1 1]
{'up': 0.25, 'down'

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
ROWS = 5
COLS = 11
X = np.indices((ROWS,COLS)).reshape(ROWS*COLS,2, order='F')
print(X)

[[ 0  5]
 [ 0  3]
 [ 1  5]
 [ 0  4]
 [ 2  5]
 [ 0  0]
 [ 3  6]
 [ 0  1]
 [ 4  6]
 [ 0  2]
 [ 0  6]
 [ 1  3]
 [ 1  6]
 [ 1  4]
 [ 2  6]
 [ 1  0]
 [ 3  7]
 [ 1  1]
 [ 4  7]
 [ 1  2]
 [ 0  7]
 [ 2  3]
 [ 1  7]
 [ 2  4]
 [ 2  7]
 [ 2  0]
 [ 3  8]
 [ 2  1]
 [ 4  8]
 [ 2  2]
 [ 0  8]
 [ 3  3]
 [ 1  8]
 [ 3  4]
 [ 2  8]
 [ 3  0]
 [ 3  9]
 [ 3  1]
 [ 4  9]
 [ 3  2]
 [ 0  9]
 [ 4  3]
 [ 1  9]
 [ 4  4]
 [ 2  9]
 [ 4  0]
 [ 3 10]
 [ 4  1]
 [ 4 10]
 [ 4  2]
 [ 0 10]
 [ 5  3]
 [ 1 10]
 [ 5  4]
 [ 2 10]]


# Policy evaluation
* Create random policy
* evaluate policy. compute the state-value  V_pi for an arbitrary policy pi. 

In [ ]:
def improve(env, agent):
    # implement policy improve
    return V

def gpi(env, agent):
    return V
        
def mccontrol(env, agent):    
    return V

In [31]:
rp = RandomPolicy(ACTIONS)

def evaluate(env, policy):
    policy.action(env._state)
    # env has env.state, env.actions
    # or env.actions(state)     
    V = np.zeros([ROWS, COLS])
    
    # playing episode    
    i=0
    print(env.isterminal(env._state))
    track=[]
    while env.isterminal(env._state) is not True and i < 1000:
        a = policy.action()
#         print('A ', a)
#         r = env.action(a)
        track.append([env._state, a, env.action(a)])
        i+=1
    
    print('i=', i)        
    print(track)

    return 1

gw.restart()
# gw.isterminal(gw._state)
evaluate(gw, rp)

False
is terminal
i= 129
[[(2, 0), 'down', -1], [(3, 0), 'left', -1], [(3, 0), 'left', -1], [(3, 0), 'up', -1], [(2, 0), 'up', -1], [(1, 0), 'up', -1], [(0, 0), 'up', -1], [(0, 0), 'left', -1], [(0, 0), 'up', -1], [(0, 0), 'down', -1], [(1, 0), 'up', -1], [(0, 0), 'down', -1], [(1, 0), 'up', -1], [(0, 0), 'up', -1], [(0, 0), 'right', -1], [(0, 1), 'left', -1], [(0, 0), 'up', -1], [(0, 0), 'down', -1], [(1, 0), 'right', -1], [(1, 1), 'down', -1], [(2, 1), 'down', -1], [(3, 1), 'down', -1], [(4, 1), 'right', -1], [(4, 2), 'right', -1], [(4, 3), 'left', -1], [(4, 2), 'down', -1], [(4, 2), 'down', -1], [(4, 2), 'down', -1], [(4, 2), 'up', -1], [(3, 2), 'right', -1], [(3, 3), 'right', -1], [(3, 4), 'right', -1], [(3, 4), 'right', -1], [(3, 4), 'down', -1], [(4, 4), 'down', -1], [(4, 4), 'up', -1], [(3, 4), 'down', -1], [(4, 4), 'left', -1], [(4, 3), 'down', -1], [(4, 3), 'left', -1], [(4, 2), 'left', -1], [(4, 1), 'up', -1], [(3, 1), 'left', -1], [(3, 0), 'right', -1], [(3, 1), 'left', -1],

1

In [88]:
# gw.action('up')
gw.restart()
print(gw._state)
# print(gw.isterminal(gw._state))

(2, 0)
